const studyLocations = [
    {
        id: 1,
        name: "National Archives of Singapore",
        type: "Public Library",
        address: "1 Canning Rise, Singapore 179868",
        totalSeats: 27,
        availableSeats: 24,
        crowdLevel: "low",
        facilities: ["quiet", "wifi", "aircon", "power", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.2966, lng: 103.8557 },
        region: "Central",
        coordinates: { lat: 1.2966, lng: 103.8557 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/About-Us/Press-Room-Publication/Annual-Reports/AR-cover-2023-2024.jpg?w=500&hash=A1E3D66FD21472999E8E3287EC20541A",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 2,
        name: "Lee Kong Chian Reference Library",
        type: "Reference Library",
        address: "100 Victoria Street, Singapore 188064",
        totalSeats: 36,
        availableSeats: 30,
        crowdLevel: "moderate",
        facilities: ["quiet", "group", "wifi", "aircon", "power", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.2967, lng: 103.854 },
        region: "Central",
        coordinates: { lat: 1.2967, lng: 103.854 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/National-Library/national-library-online.png?w=500&hash=028C92A24718FD50E1DED79C2D567DBA",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "power", position: "center", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "window", position: "window", status: "available" },
            { id: 17, type: "window", position: "window", status: "available" },
            { id: 18, type: "window", position: "window", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" },
            { id: 31, type: "regular", position: "center", status: "available" },
            { id: 32, type: "regular", position: "corner", status: "available" },
            { id: 33, type: "regular", position: "corner", status: "available" },
            { id: 34, type: "regular", position: "center", status: "available" },
            { id: 35, type: "regular", position: "center", status: "occupied" },
            { id: 36, type: "regular", position: "wall", status: "available" }
        ]
    },
    {
        id: 3,
        name: "Tampines Regional Library",
        type: "Regional Library",
        address: "1 Tampines Walk, Our Tampines Hub #02-01, Singapore 528523",
        totalSeats: 35,
        availableSeats: 28,
        crowdLevel: "moderate",
        facilities: ["quiet", "wifi", "aircon", "power", "wheelchair"],
        region: "East",
        coordinates: { lat: 1.3521, lng: 103.9448 },
        region: "East",
        coordinates: { lat: 1.3521, lng: 103.9448 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/TRL/Library-Images/Tampines-Regional-Library-Supplementary-Images-1-Singapore-Collection.jpg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "power", position: "center", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "window", position: "window", status: "available" },
            { id: 17, type: "window", position: "window", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" },
            { id: 31, type: "regular", position: "center", status: "available" },
            { id: 32, type: "regular", position: "corner", status: "available" },
            { id: 33, type: "regular", position: "corner", status: "available" },
            { id: 34, type: "regular", position: "center", status: "available" },
            { id: 35, type: "regular", position: "center", status: "occupied" }
        ]
    },
    {
        id: 4,
        name: "Jurong Regional Library",
        type: "Regional Library",
        address: "21 Jurong East Central 1, Singapore 609732",
        totalSeats: 32,
        availableSeats: 26,
        crowdLevel: "moderate",
        facilities: ["quiet", "group", "cafe", "wifi", "aircon", "wheelchair"],
        region: "West",
        coordinates: { lat: 1.3329, lng: 103.7436 },
        region: "West",
        coordinates: { lat: 1.3329, lng: 103.7436 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/JRL/Library-Images/Jurong-Regional-Library-Supplementary-Images-1-VAT.jpg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "window", position: "window", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" },
            { id: 31, type: "regular", position: "center", status: "available" },
            { id: 32, type: "regular", position: "corner", status: "available" }
        ]
    },
        {
        id: 5,
        name: "Woodlands Regional Library",
        type: "Regional Library",
        address: "900 South Woodlands Drive, #01-03, Singapore 730900",
        totalSeats: 59,
        availableSeats: 49,
        crowdLevel: "low",
        facilities: ["quiet", "group", "cafe", "wifi", "aircon", "power", "wheelchair"],
        region: "North",
        coordinates: { lat: 1.4361, lng: 103.7864 },
        region: "North",
        coordinates: { lat: 1.4361, lng: 103.7864 },
        hasFloors: true,
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/WRL/Library-Images/Woodlands-Regional-Library-Supplementary-Images-1-MakeIT.jpg",
        floors: [
            {
                floorNumber: 1,
                floorName: "Level 1 - Main Study Area",
                description: "Main library collection with reading areas and circulation counter",
                totalSeats: 24,
                availableSeats: 20,
                facilities: ["quiet", "wifi", "aircon", "power"],
                layoutType: "grid",
                image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/WRL/Library-Images/Woodlands-Regional-Library-1.jpg",
                seats: [
                    { id: "S51", type: "power", position: "center", status: "available" },
                    { id: "S52", type: "power", position: "center", status: "occupied" },
                    { id: "S53", type: "power", position: "center", status: "available" },
                    { id: "S54", type: "power", position: "center", status: "available" },
                    { id: "S55", type: "power", position: "center", status: "available" },
                    { id: "S56", type: "power", position: "center", status: "available" },
                    { id: "S57", type: "power", position: "center", status: "available" },
                    { id: "S58", type: "window", position: "window", status: "occupied" },
                    { id: "S59", type: "power", position: "center", status: "available" },
                    { id: "S60", type: "power", position: "center", status: "available" },
                    { id: "S61", type: "power", position: "center", status: "available" },
                    { id: "S62", type: "power", position: "center", status: "available" },
                    { id: "S63", type: "regular", position: "center", status: "available" },
                    { id: "S64", type: "regular", position: "center", status: "occupied" },
                    { id: "S65", type: "regular", position: "center", status: "available" },
                    { id: "S66", type: "regular", position: "center", status: "available" },
                    { id: "S67", type: "regular", position: "center", status: "available" },
                    { id: "S68", type: "regular", position: "center", status: "available" },
                    { id: "S69", type: "regular", position: "center", status: "available" },
                    { id: "S70", type: "regular", position: "center", status: "occupied" },
                    { id: "S71", type: "regular", position: "center", status: "available" },
                    { id: "S72", type: "regular", position: "center", status: "available" },
                    { id: "S73", type: "regular", position: "center", status: "available" },
                    { id: "S74", type: "regular", position: "center", status: "available" }
                ]
            },
            {
                floorNumber: 2,
                floorName: "Level 2 - Lounge Reading Area",
                description: "Comfortable lounge seating with sofas for relaxed reading and study",
                totalSeats: 11,
                availableSeats: 9,
                facilities: ["group", "wifi", "aircon", "power"],
                layoutType: "lounge",
                image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/WRL/Library-Images/Woodlands-Regional-Library-Supplementary-Images-1-MakeIT.jpg",
                seats: [
                    { id: "S33", type: "power", position: "center", status: "available" },
                    { id: "S34", type: "power", position: "center", status: "occupied" },
                    { id: "S35", type: "power", position: "center", status: "available" },
                    { id: "S36", type: "regular", position: "center", status: "available" },
                    { id: "S37", type: "regular", position: "center", status: "available" },
                    { id: "S38", type: "regular", position: "center", status: "available" },
                    { id: "S39", type: "window", position: "window", status: "available" },
                    { id: "S40", type: "window", position: "window", status: "occupied" },
                    { id: "S41", type: "regular", position: "center", status: "available" },
                    { id: "S42", type: "regular", position: "center", status: "available" },
                    { id: "S43", type: "regular", position: "center", status: "available" }
                ]
            },
            {
                floorNumber: 3,
                floorName: "Level 3 - Multimedia Study Area",
                description: "Silent study area with multimedia resources and individual carrels",
                totalSeats: 24,
                availableSeats: 20,
                facilities: ["quiet", "wifi", "aircon", "power"],
                layoutType: "multimedia",
                image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
                seats: [
                    { id: "S134", type: "power", position: "center", status: "available" },
                    { id: "S135", type: "power", position: "center", status: "available" },
                    { id: "S136", type: "power", position: "center", status: "available" },
                    { id: "S137", type: "power", position: "center", status: "occupied" },
                    { id: "S138", type: "power", position: "center", status: "available" },
                    { id: "S139", type: "power", position: "center", status: "available" },
                    { id: "S140", type: "power", position: "center", status: "available" },
                    { id: "S141", type: "power", position: "center", status: "available" },
                    { id: "S142", type: "power", position: "center", status: "available" },
                    { id: "S143", type: "window", position: "window", status: "occupied" },
                    { id: "S144", type: "power", position: "center", status: "available" },
                    { id: "S145", type: "power", position: "center", status: "available" },
                    { id: "S146", type: "regular", position: "center", status: "available" },
                    { id: "S147", type: "regular", position: "center", status: "available" },
                    { id: "S148", type: "regular", position: "center", status: "available" },
                    { id: "S149", type: "regular", position: "center", status: "occupied" },
                    { id: "S150", type: "regular", position: "center", status: "available" },
                    { id: "S151", type: "regular", position: "center", status: "available" },
                    { id: "S152", type: "regular", position: "center", status: "available" },
                    { id: "S153", type: "regular", position: "center", status: "available" },
                    { id: "S154", type: "regular", position: "center", status: "available" },
                    { id: "S155", type: "regular", position: "center", status: "occupied" },
                    { id: "S156", type: "regular", position: "center", status: "available" },
                    { id: "S157", type: "regular", position: "center", status: "available" }
                ]
            }
        ]
    },
    {
        id: 6,
        name: "Central Public Library",
        type: "Public Library",
        address: "100 Victoria Street, Singapore 188064",
        totalSeats: 28,
        availableSeats: 22,
        crowdLevel: "moderate",
        facilities: ["quiet", "group", "cafe", "wifi", "aircon", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.2967, lng: 103.854 },
        region: "Central",
        coordinates: { lat: 1.2967, lng: 103.854 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/CLL/Library-Images/Central-Public-Library-Supplementary-Images-1-Childrens-Biodiversity-Library-by-Singapore-Oceanarium.jpg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" }
        ]
    },
    {
        id: 7,
        name: "Bishan Public Library",
        type: "Public Library",
        address: "5 Bishan Place, #01-01, Singapore 579841",
        totalSeats: 26,
        availableSeats: 21,
        crowdLevel: "low",
        facilities: ["quiet", "cafe", "wifi", "aircon", "power", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.3516, lng: 103.8493 },
        region: "Central",
        coordinates: { lat: 1.3516, lng: 103.8493 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/BIPL/Library-Images/Bishan-Public-Library-Supplementary-Images-1-Internal-View-of-Pod-Alcoves.jpeg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 8,
        name: "Ang Mo Kio Public Library",
        type: "Public Library",
        address: "4300 Ang Mo Kio Ave 6, Singapore 569842",
        totalSeats: 24,
        availableSeats: 19,
        crowdLevel: "moderate",
        facilities: ["quiet", "group", "cafe", "wifi", "aircon"],
        region: "North",
        coordinates: { lat: 1.3691, lng: 103.8454 },
        region: "North",
        coordinates: { lat: 1.3691, lng: 103.8454 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/AMKPL/Library-Images/Ang-Mo-Kio-Public-Library-Supplementary-Images-1-Multimedia-Stations-and-Study-Area.jpg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 9,
        name: "Bedok Public Library",
        type: "Public Library",
        address: "11 Bedok North Street 1, Singapore 469662",
        totalSeats: 22,
        availableSeats: 18,
        crowdLevel: "moderate",
        facilities: ["quiet", "wifi", "aircon", "power"],
        region: "East",
        coordinates: { lat: 1.3236, lng: 103.9273 },
        region: "East",
        coordinates: { lat: 1.3236, lng: 103.9273 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/BEPL/Library-Images/Bedok-Public-Library-Supplementary-Images-1-Teens-Study-and-Reading-Area.jpeg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 10,
        name: "Toa Payoh Public Library",
        type: "Public Library",
        address: "6 Toa Payoh Central, Singapore 319191",
        totalSeats: 20,
        availableSeats: 16,
        crowdLevel: "low",
        facilities: ["quiet", "wifi", "aircon", "power", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.3343, lng: 103.8563 },
        region: "Central",
        coordinates: { lat: 1.3343, lng: 103.8563 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/TPPL/Library-Images/Toa-Payoh-Public-Library-Supplementary-Images-1-Early-Literacy-Section.jpeg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" }
        ]
    },
    {
        id: 11,
        name: "Sengkang Public Library",
        type: "Public Library",
        address: "1 Sengkang Square, #03-28, Singapore 545078",
        totalSeats: 24,
        availableSeats: 20,
        crowdLevel: "low",
        facilities: ["quiet", "wifi", "aircon", "power", "wheelchair"],
        region: "North",
        coordinates: { lat: 1.3915, lng: 103.8947 },
        region: "North",
        coordinates: { lat: 1.3915, lng: 103.8947 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/SKPL/Library-Images/Sengkang-Public-Library-Supplementary-Images-1-Early-Literacy-Area.jpeg",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 12,
        name: "Punggol Regional Library",
        type: "Regional Library",
        address: "1 Punggol Drive, Waterway Point #04-15, Singapore 828629",
        totalSeats: 34,
        availableSeats: 28,
        crowdLevel: "moderate",
        facilities: ["quiet", "cafe", "wifi", "aircon", "power", "wheelchair"],
        region: "North-East",
        coordinates: { lat: 1.4058, lng: 103.9014 },
        region: "North-East",
        coordinates: { lat: 1.4058, lng: 103.9014 },
        image: "https://www.nlb.gov.sg/main/-/media/NLBMedia/Images/Visit-Us/Libraries/PRL/Library-Images/Punggol-Regional-Library-Supplementary-Images-1-SparkLab-TM.JPG",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "power", position: "center", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "window", position: "window", status: "available" },
            { id: 17, type: "window", position: "window", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" },
            { id: 31, type: "regular", position: "center", status: "available" },
            { id: 32, type: "regular", position: "corner", status: "available" },
            { id: 33, type: "regular", position: "corner", status: "available" },
            { id: 34, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 13,
        name: "NUS Central Library",
        type: "University Library",
        address: "12 Kent Ridge Crescent, Singapore 119275",
        totalSeats: 35,
        availableSeats: 29,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "power", "quiet", "group", "wheelchair"],
        region: "West",
        coordinates: { lat: 1.2966, lng: 103.7764 },
        region: "West",
        coordinates: { lat: 1.2966, lng: 103.7764 },
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "power", position: "center", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "window", position: "window", status: "available" },
            { id: 17, type: "window", position: "window", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" },
            { id: 31, type: "regular", position: "center", status: "available" },
            { id: 32, type: "regular", position: "corner", status: "available" },
            { id: 33, type: "regular", position: "corner", status: "available" },
            { id: 34, type: "regular", position: "center", status: "available" },
            { id: 35, type: "regular", position: "center", status: "occupied" }
        ]
    },
    {
        id: 16,
        name: "NTU Art, Design & Media Library",
        type: "University Library",
        address: "81 Nanyang Drive, Singapore 637458",
        totalSeats: 25,
        availableSeats: 20,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "power", "quiet", "group", "wheelchair"],
        region: "West",
        coordinates: { lat: 1.3483, lng: 103.6831 },
        region: "West",
        coordinates: { lat: 1.3483, lng: 103.6831 },
        image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 17,
        name: "SMU Li Ka Shing Library",
        type: "University Library",
        address: "81 Victoria Street, Singapore 188065",
        totalSeats: 30,
        availableSeats: 25,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "power", "quiet", "group", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.2966, lng: 103.8496 },
        region: "Central",
        coordinates: { lat: 1.2966, lng: 103.8496 },
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "power", position: "corner", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "window", position: "window", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" },
            { id: 29, type: "regular", position: "center", status: "available" },
            { id: 30, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 18,
        name: "SMU Kwa Geok Choo Law Library",
        type: "University Library",
        address: "55 Armenian Street, Singapore 179943",
        totalSeats: 26,
        availableSeats: 21,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "power", "quiet", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.2945, lng: 103.8489 },
        region: "Central",
        coordinates: { lat: 1.2945, lng: 103.8489 },
        image: "https://images.unsplash.com/photo-1495954484750-af469f2f9be5?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 19,
        name: "SUTD Library",
        type: "University Library",
        address: "8 Somapah Road, Singapore 487372",
        totalSeats: 28,
        availableSeats: 23,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "power", "quiet", "group", "wheelchair"],
        region: "East",
        coordinates: { lat: 1.3404, lng: 103.9635 },
        region: "East",
        coordinates: { lat: 1.3404, lng: 103.9635 },
        image: "https://images.unsplash.com/photo-1519452575417-564c1401ecc0?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "power", position: "corner", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "window", position: "window", status: "available" },
            { id: 14, type: "window", position: "window", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" },
            { id: 25, type: "regular", position: "corner", status: "available" },
            { id: 26, type: "regular", position: "center", status: "available" },
            { id: 27, type: "regular", position: "center", status: "available" },
            { id: 28, type: "regular", position: "wall", status: "occupied" }
        ]
    },
    {
        id: 20,
        name: "SIT Library @ Punggol",
        type: "University Library",
        address: "10 Dover Drive, Singapore 138683",
        totalSeats: 24,
        availableSeats: 19,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "power", "quiet", "group", "wheelchair"],
        region: "North-East",
        coordinates: { lat: 1.4058, lng: 103.9014 },
        region: "North-East",
        coordinates: { lat: 1.4058, lng: 103.9014 },
        image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "power", position: "center", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "window", position: "window", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" },
            { id: 23, type: "regular", position: "center", status: "available" },
            { id: 24, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 21,
        name: "LASALLE College Library",
        type: "Arts Institution Library",
        address: "1 McNally Street, Singapore 187940",
        totalSeats: 22,
        availableSeats: 18,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "power", "quiet", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.3016, lng: 103.8554 },
        region: "Central",
        coordinates: { lat: 1.3016, lng: 103.8554 },
        image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 24,
        name: "Tampines West CC Study Corner",
        type: "Community Centre",
        address: "2 Tampines Street 41, Singapore 529204",
        totalSeats: 16,
        availableSeats: 14,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "quiet", "wheelchair"],
        region: "East",
        coordinates: { lat: 1.3521, lng: 103.9448 },
        region: "East",
        coordinates: { lat: 1.3521, lng: 103.9448 },
        image: "https://images.unsplash.com/photo-1497486751825-1233686d5d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "window", position: "window", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "regular", position: "corner", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 25,
        name: "Bishan CC Learning Hub",
        type: "Community Centre",
        address: "51 Bishan Street 13, Singapore 579799",
        totalSeats: 20,
        availableSeats: 18,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "quiet", "power", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.3516, lng: 103.8493 },
        region: "Central",
        coordinates: { lat: 1.3516, lng: 103.8493 },
        image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" }
        ]
    },
    {
        id: 26,
        name: "Jurong East CC Study Space",
        type: "Community Centre",
        address: "21 Jurong East Street 31, Singapore 609517",
        totalSeats: 18,
        availableSeats: 16,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "quiet", "wheelchair"],
        region: "West",
        coordinates: { lat: 1.3329, lng: 103.7436 },
        region: "West",
        coordinates: { lat: 1.3329, lng: 103.7436 },
        image: "https://images.unsplash.com/photo-1581833971358-2c8b550f87b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 27,
        name: "Ang Mo Kio CC Study Room",
        type: "Community Centre",
        address: "721 Ang Mo Kio Avenue 8, Singapore 560721",
        totalSeats: 15,
        availableSeats: 13,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "quiet", "wheelchair"],
        region: "North",
        coordinates: { lat: 1.3691, lng: 103.8454 },
        region: "North",
        coordinates: { lat: 1.3691, lng: 103.8454 },
        image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "window", position: "window", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "regular", position: "corner", status: "available" },
            { id: 9, type: "regular", position: "corner", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 28,
        name: "Bedok CC Quiet Study Area",
        type: "Community Centre",
        address: "850 Bedok North Street 2, Singapore 460850",
        totalSeats: 22,
        availableSeats: 19,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "quiet", "power", "wheelchair"],
        region: "East",
        coordinates: { lat: 1.3236, lng: 103.9273 },
        region: "East",
        coordinates: { lat: 1.3236, lng: 103.9273 },
        image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "power", position: "center", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "window", position: "window", status: "available" },
            { id: 11, type: "window", position: "window", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" },
            { id: 20, type: "regular", position: "wall", status: "available" },
            { id: 21, type: "regular", position: "center", status: "occupied" },
            { id: 22, type: "regular", position: "center", status: "available" }
        ]
    },
    {
        id: 29,
        name: "Toa Payoh CC Learning Space",
        type: "Community Centre",
        address: "93 Toa Payoh Central, Singapore 319194",
        totalSeats: 14,
        availableSeats: 12,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "quiet", "wheelchair"],
        region: "Central",
        coordinates: { lat: 1.3343, lng: 103.8563 },
        region: "Central",
        coordinates: { lat: 1.3343, lng: 103.8563 },
        image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "window", position: "window", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "regular", position: "corner", status: "available" },
            { id: 9, type: "regular", position: "corner", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" }
        ]
    },
    {
        id: 30,
        name: "Woodlands CC Study Corner",
        type: "Community Centre",
        address: "1 Woodlands Street 83, Singapore 738523",
        totalSeats: 17,
        availableSeats: 15,
        crowdLevel: "low",
        facilities: ["wifi", "aircon", "quiet", "wheelchair"],
        region: "North",
        coordinates: { lat: 1.4361, lng: 103.7864 },
        region: "North",
        coordinates: { lat: 1.4361, lng: 103.7864 },
        image: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "regular", position: "corner", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" }
        ]
    },
    {
        id: 31,
        name: "Clementi CC Study Hall",
        type: "Community Centre",
        address: "220 Clementi Avenue 4, Singapore 129880",
        totalSeats: 19,
        availableSeats: 17,
        crowdLevel: "moderate",
        facilities: ["wifi", "aircon", "quiet", "power", "wheelchair"],
        region: "West",
        coordinates: { lat: 1.3162, lng: 103.7649 },
        region: "West",
        coordinates: { lat: 1.3162, lng: 103.7649 },
        image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        seats: [
            { id: 1, type: "power", position: "corner", status: "available" },
            { id: 2, type: "power", position: "center", status: "available" },
            { id: 3, type: "power", position: "center", status: "available" },
            { id: 4, type: "power", position: "wall", status: "available" },
            { id: 5, type: "power", position: "center", status: "available" },
            { id: 6, type: "window", position: "window", status: "available" },
            { id: 7, type: "window", position: "window", status: "occupied" },
            { id: 8, type: "window", position: "window", status: "available" },
            { id: 9, type: "window", position: "window", status: "available" },
            { id: 10, type: "regular", position: "center", status: "available" },
            { id: 11, type: "regular", position: "center", status: "available" },
            { id: 12, type: "regular", position: "wall", status: "available" },
            { id: 13, type: "regular", position: "center", status: "available" },
            { id: 14, type: "regular", position: "center", status: "occupied" },
            { id: 15, type: "regular", position: "center", status: "available" },
            { id: 16, type: "regular", position: "corner", status: "available" },
            { id: 17, type: "regular", position: "corner", status: "available" },
            { id: 18, type: "regular", position: "center", status: "available" },
            { id: 19, type: "regular", position: "center", status: "available" }
        ]
    }
];

let bookings = [];
let favorites = [];

function loadBookings() {
    const saved = localStorage.getItem('studyspace-bookings');
    return saved ? JSON.parse(saved) : [];
}

function saveBookings(bookings) {
    localStorage.setItem('studyspace-bookings', JSON.stringify(bookings));
}

function loadFavorites() {
    const saved = localStorage.getItem('studyspace-favorites');
    return saved ? JSON.parse(saved) : [];
}

function saveFavorites(favorites) {
    localStorage.setItem('studyspace-favorites', JSON.stringify(favorites));
}

